{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1734b830-969c-42d3-875c-07c92c50b68d",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Equipment:\n",
    "    def __init__(self, name, type, capacity, power, section, section_type, depth, length, width, utilization, mtbf, mttr):\n",
    "        self.name = name\n",
    "        self.type = type\n",
    "        self.capacity = capacity\n",
    "        self.power = power\n",
    "        self.section = section\n",
    "        self.section_type = section_type\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "        self.utilization = utilization\n",
    "        self.mtbf = mtbf\n",
    "        self.mttr = mttr\n",
    "class Environment:\n",
    "    def __init__(self, name, type, capacity, power, section, section_type, depth, length, width, equipment, utilization, mtbf, mttr):\n",
    "        self.name = name\n",
    "        self.type = type\n",
    "        self.capacity = capacity\n",
    "        self.power = power\n",
    "        self.section = section\n",
    "        self.section_type = section_type\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "        self.equipment = equipment\n",
    "        self.utilization = utilization\n",
    "        self.mtbf = mtbf\n",
    "        self.mttr = mttr\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "655fe5e4-6741-4d7a-bc4f-c62394e16066",
   "metadata": {},
   "outputs": [],
   "source": [
    "Develop Equipment specs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7e5f9637-60a2-466d-9ac7-d368d90edc9b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Drill1 Specs:\n",
      "Capacity: ['2000m']\n",
      "Power: ['4500kW']\n",
      "\n",
      "Drill2 Specs:\n",
      "Capacity: ['1500m']\n",
      "Power: ['3500kW']\n",
      "\n",
      "Truck1 Specs:\n",
      "Capacity: ['100t']\n",
      "Power: ['5850HP']\n",
      "\n",
      "Truck2 Specs:\n",
      "Capacity: ['100t']\n",
      "Power: ['5850HP']\n",
      "\n",
      "Loader1 Specs:\n",
      "Capacity: ['12yd3']\n",
      "Power: ['2000kW']\n",
      "\n",
      "nan Specs:\n",
      "Capacity: []\n",
      "Power: []\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "# Load CSV file into a DataFrame\n",
    "file_path = 'simulation.csv'  # Replace with your actual file path\n",
    "df = pd.read_csv(file_path)\n",
    "# Extract unique equipment names\n",
    "equipment_names = df['Equipment'].unique()\n",
    "# Initialize a dictionary to store equipment specs\n",
    "equipment_specs = {}\n",
    "# Iterate through each equipment type\n",
    "for equipment_name in equipment_names:\n",
    "    # Filter rows for the current equipment\n",
    "    equipment_df = df[df['Equipment'] == equipment_name]\n",
    "    # Extract and store unique capacity and power values\n",
    "    capacity_values = equipment_df['Capacity'].unique()\n",
    "    power_values = equipment_df['Power'].unique()\n",
    "    # Store equipment specs in the dictionary\n",
    "    equipment_specs[equipment_name] = {\n",
    "        'Capacity': capacity_values.tolist(),\n",
    "        'Power': power_values.tolist()\n",
    "    }\n",
    "# Print the equipment specifications\n",
    "for equipment, specs in equipment_specs.items():\n",
    "    print(f\"{equipment} Specs:\")\n",
    "    print(f\"Capacity: {specs['Capacity']}\")\n",
    "    print(f\"Power: {specs['Power']}\\n\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "raw",
   "id": "51693c4f-c226-4473-82c6-76761bf0ce6f",
   "metadata": {},
   "source": [
    "#Develop Integration with Drilling and Hauling"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8f3cc5bc-b215-420c-9a09-7480afb55f88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulating drilling with Drill1: 200m depth, 1000m length, 800m width.\n",
      "Hauling with Truck1: 10250m length, 400m width.\n",
      "Loading with Loader1.\n",
      "\n",
      "\n",
      "Hauling with Truck2: 10250m length, 400m width.\n",
      "Loading with Loader1.\n",
      "\n",
      "\n",
      "Simulating drilling with Drill2: 200m depth, 1000m length, 800m width.\n",
      "Hauling with Truck1: 10250m length, 400m width.\n",
      "Loading with Loader1.\n",
      "\n",
      "\n",
      "Hauling with Truck2: 10250m length, 400m width.\n",
      "Loading with Loader1.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "csv_data = \"\"\"\n",
    "Drilling,Type,Capacity,Power,Cost,Section,Type,AreaDepth,AreaLength,AreaWidth\n",
    "Drill1,Rotary,2000m,4500kW,NA,East,Surface,200m,1000m,800m\n",
    "Drill2,Hammer,1500m,3500kW,NA,East,Surface,200m,1000m,800m\n",
    "Truck1,Diesel,100t,5850HP,NA,East,Surface,200m,10250m,400m\n",
    "Truck2,Diesel,100t,5850HP,NA,East,Surface,200m,10250m,400m\n",
    "Loader1,Electrical,12yd3,2000kW,NA,West,Underground,200m,12081m,400m\n",
    "Loader1,Electrical,12yd3,2000kW,NA,West,Underground,200m,10250m,400m\n",
    "Loader1,Electrical,12yd3,2000kW,NA,West,Underground,200m,10250m,400m\n",
    "Loader1,Electrical,12yd3,2000kW,NA,West,Underground,800m,500m,10m\n",
    "\"\"\"\n",
    "# Split CSV data into lines\n",
    "lines = csv_data.strip().split('\\n')\n",
    "# Extract relevant information into dictionaries\n",
    "drilling_data = {}\n",
    "hauling_data = {}\n",
    "for line in lines[1:]:  # Skip header\n",
    "    fields = line.split(',')\n",
    "    equipment_type = fields[0].strip()\n",
    "    if \"Drill\" in equipment_type:\n",
    "        drilling_data[equipment_type] = {\n",
    "            'type': fields[1].strip(),\n",
    "            'capacity': fields[2].strip(),\n",
    "            'power': fields[3].strip(),\n",
    "            'area_depth': fields[7].strip(),\n",
    "            'area_length': fields[8].strip(),\n",
    "            'area_width': fields[9].strip(),\n",
    "        }\n",
    "    elif \"Truck\" in equipment_type:\n",
    "        hauling_data[equipment_type] = {\n",
    "            'type': fields[1].strip(),\n",
    "            'capacity': fields[2].strip(),\n",
    "            'power': fields[3].strip(),\n",
    "            'area_length': fields[8].strip(),\n",
    "            'area_width': fields[9].strip(),\n",
    "        }\n",
    "# Simulation function\n",
    "def simulate_drilling_and_hauling(drilling_data, hauling_data):\n",
    "    for drill, drill_info in drilling_data.items():\n",
    "        print(f\"Simulating drilling with {drill}: {drill_info['area_depth']} depth, {drill_info['area_length']} length, {drill_info['area_width']} width.\")\n",
    "        # Simulate hauling after drilling\n",
    "        for truck, truck_info in hauling_data.items():\n",
    "            print(f\"Hauling with {truck}: {truck_info['area_length']} length, {truck_info['area_width']} width.\")\n",
    "            # Simulate loading with loader\n",
    "            print(\"Loading with Loader1.\")\n",
    "            # Add any additional simulation logic as needed\n",
    "            # Calculate costs or other metrics based on simulation\n",
    "            print(\"\\n\")\n",
    "# Run the simulation\n",
    "simulate_drilling_and_hauling(drilling_data, hauling_data)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "98124987-ca22-4e8d-b048-1974ff3ebe39",
   "metadata": {},
   "outputs": [],
   "source": [
    "#constructing Mine Sections"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "046c3549-f292-4a4b-8b4b-eb75443558d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulating drilling with Drill1 in Surface section - SectionPlace: East:\n",
      "  Capacity: 2000m, Power: 4500kW\n",
      "  Hauling with Truck1 in Surface section - SectionPlace: East:\n",
      "    Capacity: 100t, Power: 5850HP\n",
      "    Constructing with Loader1 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader2 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader3 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader4 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "  Hauling with Truck2 in Surface section - SectionPlace: East:\n",
      "    Capacity: 100t, Power: 5850HP\n",
      "    Constructing with Loader1 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader2 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader3 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader4 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "Simulating drilling with Drill2 in Surface section - SectionPlace: East:\n",
      "  Capacity: 1500m, Power: 3500kW\n",
      "  Hauling with Truck1 in Surface section - SectionPlace: East:\n",
      "    Capacity: 100t, Power: 5850HP\n",
      "    Constructing with Loader1 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader2 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader3 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader4 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "  Hauling with Truck2 in Surface section - SectionPlace: East:\n",
      "    Capacity: 100t, Power: 5850HP\n",
      "    Constructing with Loader1 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader2 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader3 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n",
      "    Constructing with Loader4 in Underground section - SectionPlace: West:\n",
      "      Capacity: 12yd3, Power: 2000kW\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# CSV data\n",
    "csv_data = \"\"\"\n",
    "Drilling,Type,Capacity,Power,Section,SectionPlace,AreaDepth,AreaLength,AreaWidth\n",
    "Drill1,Rotary,2000m,4500kW,Surface,East,200m,1000m,800m\n",
    "Drill2,Hammer,1500m,3500kW,Surface,East,200m,1000m,800m\n",
    "Truck1,Diesel,100t,5850HP,Surface,East,200m,10250m,400m\n",
    "Truck2,Diesel,100t,5850HP,Surface,East,200m,10250m,400m\n",
    "Loader1,Electrical,12yd3,2000kW,Underground,West,200m,12081m,400m\n",
    "Loader2,Electrical,12yd3,2000kW,Underground,West,200m,10250m,400m\n",
    "Loader3,Electrical,12yd3,2000kW,Underground,West,200m,10250m,400m\n",
    "Loader4,Electrical,12yd3,2000kW,Underground,West,800m,500m,10m\n",
    "\"\"\"\n",
    "# Split CSV data into lines\n",
    "lines = csv_data.strip().split('\\n')\n",
    "# Extract relevant information into dictionaries\n",
    "drilling_data = {}\n",
    "hauling_data = {}\n",
    "construction_data = {}\n",
    "for line in lines[1:]:  # Skip header\n",
    "    fields = line.split(',')\n",
    "    equipment_type = fields[0].strip()  # extracts the type of equipment\n",
    "    if \"Drill\" in equipment_type:  # checks if drill equipment is present and if present extracts the data\n",
    "        drilling_data[equipment_type] = {\n",
    "            'capacity': fields[2].strip(),\n",
    "            'power': fields[3].strip(),\n",
    "            'section': fields[4].strip(),\n",
    "            'section_place': fields[5].strip(),  # Include SectionPlace instead of Type\n",
    "        }\n",
    "    elif \"Truck\" in equipment_type:  # if truck data is present then it extracts truck data\n",
    "        hauling_data[equipment_type] = {\n",
    "            'capacity': fields[2].strip(),\n",
    "            'power': fields[3].strip(),\n",
    "            'section': fields[4].strip(),\n",
    "            'section_place': fields[5].strip(),  # Include SectionPlace instead of Type\n",
    "        }\n",
    "    elif \"Loader\" in equipment_type:  # if loader data is present then it extracts truck data\n",
    "        construction_data[equipment_type] = {\n",
    "            'capacity': fields[2].strip(),\n",
    "            'power': fields[3].strip(),\n",
    "            'section': fields[4].strip(),\n",
    "            'section_place': fields[5].strip(),  # Include SectionPlace instead of Type\n",
    "        }\n",
    "# Simulation function\n",
    "def simulate_mine_operations(drilling_data, hauling_data, construction_data):\n",
    "    for drill, drill_info in drilling_data.items():\n",
    "        print(f\"Simulating drilling with {drill} in {drill_info['section']} section - SectionPlace: {drill_info['section_place']}:\")\n",
    "        print(f\"  Capacity: {drill_info['capacity']}, Power: {drill_info['power']}\")\n",
    "        # Simulate hauling after drilling\n",
    "        for truck, truck_info in hauling_data.items():\n",
    "            print(f\"  Hauling with {truck} in {truck_info['section']} section - SectionPlace: {truck_info['section_place']}:\")\n",
    "            print(f\"    Capacity: {truck_info['capacity']}, Power: {truck_info['power']}\")\n",
    "            # Simulate loading with loader\n",
    "            for loader, loader_info in construction_data.items():\n",
    "                print(f\"    Constructing with {loader} in {loader_info['section']} section - SectionPlace: {loader_info['section_place']}:\")\n",
    "                print(f\"      Capacity: {loader_info['capacity']}, Power: {loader_info['power']}\")\n",
    "                # Add any additional simulation logic as needed\n",
    "                # Calculate costs or other metrics based on simulation\n",
    "                print(\"\\n\")\n",
    "# Run the simulation\n",
    "simulate_mine_operations(drilling_data, hauling_data, construction_data)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2d8880fe-aa9f-4b8d-85f0-997780f4cc6a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Environmental Specifications"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "04546c98-1962-492e-885a-538aea15a9eb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulation 1: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width : 800m m\n",
      "\n",
      "Simulation 2: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width : 800m m\n",
      "\n",
      "Simulation 3: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 4: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 12080 m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 5: \n",
      "Environment: Surface\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 6: \n",
      "Environment: Underground\n",
      "Depth: 200m m\n",
      "Length: 12081 m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 7: \n",
      "Environment: Underground\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 8: \n",
      "Environment: Underground\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width : 400m  m\n",
      "\n",
      "Simulation 9: \n",
      "Environment: Underground\n",
      "Depth: 800m m\n",
      "Length: 500m m\n",
      "Width : 10m m\n",
      "\n",
      "Simulation 10: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 11: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 12: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 13: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n",
      "Simulation 14: \n",
      "Environment: \n",
      "Depth:  m\n",
      "Length:  m\n",
      "Width :  m\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# develop environment specs\n",
    "import csv\n",
    "import pandas as pd\n",
    "# creating class\n",
    "class Environment:\n",
    "    def __init__(self, type, depth, length, width):# creating constructor\n",
    "        self.type = type\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width= width\n",
    "    def get_environment_specs(self):# function to environment_specs\n",
    "        return {\n",
    "            'depth': self.depth,\n",
    "            'length': self.length,\n",
    "            'width': self.width\n",
    "        }\n",
    "class MiningSimulation:# creating mining simulation\n",
    "    def __init__(self, environment):# creating constructor\n",
    "        self.environment = environment\n",
    "def read_data_from_file(file_path):\n",
    "    with open(file_path, 'r') as csv_file:\n",
    "        reader = csv.DictReader(csv_file)\n",
    "        environments=[]\n",
    "        for row in reader:\n",
    "            environment=Environment(\n",
    "                type=row['Type'],\n",
    "                depth=row['Depth'],\n",
    "                length=row['Length'],\n",
    "                width=row['Width']\n",
    "            )\n",
    "            environments.append(environment)\n",
    "        return environments\n",
    "# Read data from CSV file\n",
    "environments = read_data_from_file('simulation.csv')\n",
    "# Initialize Simulation\n",
    "mine_simulations = []\n",
    "for environment in environments:\n",
    "    mine_simulation=MiningSimulation(environment)\n",
    "    mine_simulations.append(mine_simulation)\n",
    "#print environment specs for each simulation\n",
    "for i, mine_simulation in enumerate(mine_simulations):\n",
    "    environment_specs=mine_simulation.environment.get_environment_specs()\n",
    "    print(f\"Simulation {i+1}: \")\n",
    "    print(f\"Environment: {mine_simulation.environment.type}\")\n",
    "    print(f\"Depth: {environment_specs['depth']} m\")\n",
    "    print(f\"Length: {environment_specs['length']} m\")\n",
    "    print(f\"Width : {environment_specs['width']} m\")\n",
    "    print()\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "66585969-c972-45c5-aefc-9874e3783bfe",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Integration with drilling and hauling"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7547f371-044d-4bf9-b50b-726ab295cf36",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulation 1:\n",
      "Drilling operation initiated in Rotary Surface section with Drill1 1\n",
      "Environment specifications: Depth=200m, Length=1000m, Width=800m\n",
      "\n",
      "Simulation 2:\n",
      "Drilling operation initiated in Hammer Surface section with Drill2 2\n",
      "Environment specifications: Depth=200m, Length=1000m, Width=800m\n",
      "\n",
      "Simulation 3:\n",
      "Hauling operation initiated in Diesel Surface section with Truck1 1\n",
      "Environment specifications: Depth=200m, Length=10250m, Width=400m \n",
      "\n",
      "Simulation 4:\n",
      "Hauling operation initiated in Diesel Surface section with Truck1 1\n",
      "Environment specifications: Depth=200m, Length=12080, Width=400m \n",
      "\n",
      "Simulation 5:\n",
      "Hauling operation initiated in Diesel Surface section with Truck2 2\n",
      "Environment specifications: Depth=200m, Length=10250m, Width=400m \n",
      "\n",
      "Simulation 6:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 7:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 8:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 9:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 10:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 11:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 12:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 13:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Simulation 14:\n",
      "No valid operation specified for the given equipment.\n",
      "\n",
      "Number of environments: 14\n",
      "Number of equipment data: 14\n",
      "Number of mine simulations: 14\n"
     ]
    }
   ],
   "source": [
    "#Develop integration with drilling, hauling\n",
    "import csv\n",
    "import pandas as pd\n",
    "class Environment:\n",
    "    def __init__(self, type, depth, length, width, type_of_section):\n",
    "        self.type = type\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "        self.type_of_section = type_of_section\n",
    "    def get_environment_specs(self):\n",
    "        return {\n",
    "            'type': self.type,\n",
    "            'depth': self.depth,\n",
    "            'length': self.length,\n",
    "            'width': self.width,\n",
    "            'type_of_section': self.type_of_section\n",
    "        }\n",
    "class Equipment:\n",
    "    def __init__(self, equipment_type, capacity, power, section, type_of_section, depth, length, width, utilization, mtbf, mttr):\n",
    "        self.equipment_type = equipment_type\n",
    "        self.capacity = capacity\n",
    "        self.power = power\n",
    "        self.section = section\n",
    "        self.type_of_section = type_of_section\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "        self.utilization = utilization\n",
    "        self.mtbf = mtbf\n",
    "        self.mttr = mttr\n",
    "class MiningSimulation:\n",
    "    def __init__(self, environment, equipment):\n",
    "        self.environment = environment\n",
    "        self.equipment = equipment\n",
    "    def perform_operations(self):\n",
    "        equipment_type_str = str(self.equipment.equipment_type).lower()\n",
    "        if equipment_type_str.startswith(\"drill\"):\n",
    "            self.drill()\n",
    "        elif equipment_type_str.startswith(\"truck\"):\n",
    "            self.haul()\n",
    "        else:\n",
    "            print(\"No valid operation specified for the given equipment.\")\n",
    "    def drill(self):\n",
    "        specs = self.environment.get_environment_specs()\n",
    "        print(f\"Drilling operation initiated in {specs['type']} {specs['type_of_section']} section with {self.equipment.equipment_type} {self.equipment.equipment_type[-1]}\")\n",
    "        print(f\"Environment specifications: Depth={specs['depth']}, Length={specs['length']}, Width={specs['width']}\")\n",
    "    def haul(self):\n",
    "        specs = self.environment.get_environment_specs()\n",
    "        print(f\"Hauling operation initiated in {specs['type']} {specs['type_of_section']} section with {self.equipment.equipment_type} {self.equipment.equipment_type[-1]}\")\n",
    "        print(f\"Environment specifications: Depth={specs['depth']}, Length={specs['length']}, Width={specs['width']}\")\n",
    "def read_data_from_file(file_path):\n",
    "    environments = []\n",
    "    equipment_data = []\n",
    "    try:\n",
    "        data = pd.read_csv(file_path)\n",
    "        for _, row in data.iterrows():\n",
    "            environment = Environment(\n",
    "                type=row['Type of Equipment'],\n",
    "                depth=row['Depth'],\n",
    "                length=row['Length'],\n",
    "                width=row['Width'],\n",
    "                type_of_section=row['Type of section']\n",
    "            )\n",
    "            environments.append(environment)\n",
    "            equipment = Equipment(\n",
    "                equipment_type=row['Equipment'],\n",
    "                capacity=row['Capacity'],\n",
    "                power=row['Power'],\n",
    "                section=row['Section'],\n",
    "                type_of_section=row['Type of section'],\n",
    "                depth=row['Depth'],\n",
    "                length=row['Length'],\n",
    "                width=row['Width'],\n",
    "                utilization=row['Utilization'],\n",
    "                mtbf=row['MTBF'],\n",
    "                mttr=row['MTTR']\n",
    "            )\n",
    "            equipment_data.append(equipment)\n",
    "    except Exception as e:\n",
    "        print(\"Error reading data from CSV:\", e)\n",
    "    return environments, equipment_data\n",
    "# Read data from CSV file\n",
    "file_path = 'simulation1.csv'\n",
    "environments, equipment_data = read_data_from_file(file_path)\n",
    "# Initialize Simulation for each environment and equipment\n",
    "mine_simulations = [MiningSimulation(env, equipment) for env, equipment in zip(environments, equipment_data)]\n",
    "# Perform operations for each Simulation\n",
    "for i, mine_simulation in enumerate(mine_simulations):\n",
    "    print(f\"Simulation {i + 1}:\")\n",
    "    mine_simulation.perform_operations()\n",
    "    print()\n",
    "# Debug prints to investigate\n",
    "print(f\"Number of environments: {len(environments)}\")\n",
    "print(f\"Number of equipment data: {len(equipment_data)}\")\n",
    "print(f\"Number of mine simulations: {len(mine_simulations)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2da51368-0d3c-4c43-a136-e1c58eb324b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Constructing Mine Sections"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "1bc73323-f959-44e5-ba5b-9b27fcc4f9bc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width: 800m m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 1000m m\n",
      "Width: 800m m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 12080 m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "East Mining Section\n",
      "Section: East and Type of section: Surface\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 12081 m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 200m m\n",
      "Length: 10250m m\n",
      "Width: 400m  m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "West Mining Section\n",
      "Section: West and Type of section: Underground\n",
      "Environment Specifications:\n",
      "Depth: 800m m\n",
      "Length: 500m m\n",
      "Width: 10m m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n",
      "nan Mining Section\n",
      "Section: nan and Type of section: nan\n",
      "Environment Specifications:\n",
      "Depth: nan m\n",
      "Length: nan m\n",
      "Width: nan m\n",
      "\n",
      "Mining Operations:\n",
      "Drilling operation initiated\n",
      "Hauling operation initiated\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "import pandas as pd\n",
    "class Environment:\n",
    "    def __init__(self, section, type_of_section, depth, length, width):\n",
    "        self.section = section\n",
    "        self.type_of_section = type_of_section\n",
    "        self.depth = depth\n",
    "        self.length = length\n",
    "        self.width = width\n",
    "    def get_environment_specs(self):\n",
    "        return {\n",
    "            'depth': self.depth,\n",
    "            'length': self.length,\n",
    "            'width': self.width\n",
    "        }\n",
    "class MiningSimulation:\n",
    "    def __init__(self, environment):\n",
    "        self.environment = environment\n",
    "    def drill(self):\n",
    "        # Placeholder for drilling functionality\n",
    "        print(\"Drilling operation initiated in\", self.environment.section)\n",
    "    def haul(self):\n",
    "        # Placeholder for hauling functionality\n",
    "        print(\"Hauling operation initiated in\", self.environment.section)\n",
    "class MiningSection:\n",
    "    def __init__(self, environment):\n",
    "        self.environment = environment\n",
    "        self.operations = {'drilling': 1, 'hauling': 1}  # Placeholder values\n",
    "    def get_section_info(self):\n",
    "        environment_specs = self.environment.get_environment_specs()\n",
    "        section_info = f\"{self.environment.section} Mining Section\"\n",
    "        section_info += f\"\\nSection: {self.environment.section} and Type of section: {self.environment.type_of_section}\"\n",
    "        section_info += \"\\nEnvironment Specifications:\"\n",
    "        section_info += f\"\\nDepth: {environment_specs['depth']} m\"\n",
    "        section_info += f\"\\nLength: {environment_specs['length']} m\"\n",
    "        section_info += f\"\\nWidth: {environment_specs['width']} m\"\n",
    "        section_info += \"\\n\\nMining Operations:\"\n",
    "        section_info += \"\\nDrilling operation initiated\"\n",
    "        section_info += \"\\nHauling operation initiated\\n\"\n",
    "        return section_info\n",
    "def read_data_from_file(file_path):\n",
    "    environments = []\n",
    "    try:\n",
    "        data = pd.read_csv(file_path)\n",
    "        for _, row in data.iterrows():\n",
    "            environment = Environment(\n",
    "                section=row['Section'],\n",
    "                type_of_section=row['Type of section'],\n",
    "                depth=(row['Depth']),\n",
    "                length=(row['Length']),\n",
    "                width=(row['Width'])\n",
    "            )\n",
    "            environments.append(environment)\n",
    "    except Exception as e:\n",
    "        print(\"Error reading data from CSV:\", e)\n",
    "    return environments\n",
    "# Read data from CSV file\n",
    "file_path = 'simulation1.csv'\n",
    "environments = read_data_from_file(file_path)\n",
    "# Initialize MiningSection for each environment\n",
    "mining_sections = [MiningSection(env) for env in environments]\n",
    "# Print information for each mining section\n",
    "for mining_section in mining_sections:\n",
    "    print(mining_section.get_section_info())\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e53b8857-c691-4085-9ca5-ad9c7dba1be1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
