trigger:
- main
pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
- script: |
    python -m pip install --upgrade pip
    python -m pip install wheel
    python -m pip install setuptools
  displayName: 'Install pip, wheel, and setuptools'
- script: |
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'
- script: |
    python -m pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run pytest'